AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Application template 
  
Globals:
  Function:
    Timeout: 3

Resources:
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./ 
      Handler: app.handler
      Runtime: nodejs10.x
      Events:
        Api:
          Type: Api
          Properties:
            Path: /test
            Method: get      
     CodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: codepipeline-service
          PolicyDocument:
            Statement:
              - Action:
                  - 'codebuild:ListBuilds'
                  - 'codebuild:ListProjects'
                  - 'codebuild:ListRepositories'
                Resource: '*'
                Effect: Allow
              - Action:
                  - 'codebuild:ListBuildsForProject'
                  - 'codebuild:BatchGetBuilds'
                  - 'codebuild:BatchGetProjects'
                  - 'codebuild:StartBuild'
                Resource: '*'
                Effect: Allow
              - Effect: Allow
                Action:
                  - 'codepipeline:PutJobSuccessResult'
                  - 'codepipeline:PutJobFailureResult'
                Resource:
                  - '*'
              - Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:GetBucketVersioning'
                Resource: '*'
                Effect: Allow
              - Action:
                  - 's3:ListBucket'
                Resource: '*'
                Effect: Allow
              - Action: 's3:PutObject'
                Resource: '*'
                Effect: Allow
              - Action: 's3:PutObject'
                Resource: '*'
                Effect: Allow
              - Action: 'codedeploy:ContinueDeployment'
                Resource: '*'
                Effect: Allow
              - Action:
                  - 'codedeploy:CreateDeployment'
                  - 'codedeploy:GetApplicationRevision'
                  - 'codedeploy:GetDeployment'
                  - 'codedeploy:GetDeploymentConfig'
                  - 'codedeploy:RegisterApplicationRevision'
                Resource: '*'
                Effect: Allow
