AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Application template 
  
Globals:
  Function:
    Timeout: 3

Resources:
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./ 
      Handler: app.handler
      Runtime: nodejs10.x
    "Version": "2012-10-17"
    "Statement": [
        "Effect": "Allow"
        "Action": [
            "iam:GetRole"
            "iam:PassRole"
        ]
        ]
        "Resource": "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /test
            Method: get
